### ISSUE TITLE
Exception loading model/blockstates

### ISSUE THREAD

**Issue by mankra** [BetterWithMods/BetterWithMods#669]
https://pastebin.com/XPibyR4k

> Caused by: java.io.FileNotFoundException: betterwithmods:blockstates/multiblock_dummy.json

Minecraft: 1.12.2
Forge: 14.23.1.2554
BWM: 2.0.14

**Comment by mankra** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4567

**Comment by primetoxinz** [comment]
Entirely unrelated, there simply isn't a model for that block because it doesn't need one. This isn't an issue

**Comment by KnightMiner** [comment]
If it does not need one, set the block to have no model like vanilla barriers do (It's one of the methods on Block)

**Comment by mankra** [comment]
> This isn't an issue

It is an issue. There are error messages in the log caused by your mod. There are ways to prevent these error messages.

Any software bloating the log file with untreated errors is bad software, not matter wether it's working or not.

You can make it better.

**Comment by mankra** [comment]
Solutions so far:

> He could simply add an empty json and the error should be away.

> If it does not need one, set the block to have no model like vanilla barriers do (It's one of the methods on Block)

**Comment by DaedalusGame** [comment]
Forge does this too, if you hadn't noticed. Examples include Dangerous Alternate Prefix errors, which we can only mute on our end, and are 99% of the time false positives, and logspam on world load as advancements try to load recipes that don't exist.

**Comment by mankra** [comment]
> Examples include Dangerous Alternate Prefix errors, which we can only mute on our end, and are 99% of the time false positives

So why do you mute them when the solution would be to report the false positive? Or are the forge devs refusing to fix it? Did they acknowledge the false positive?

> and logspam on world load as advancements try to load recipes that don't exist

An advancement trying to load a non-existent recipe sounds like an error, so why would it be spam to log that? Shouldn't it be corrected by fixing the advancements or adding the missing recipe?

Besides, the errors of other people do not justify the own ones. Don't you see that this attitude makes you lazy and your product worse?

**Comment by primetoxinz** [comment]
If you want to fix it feel free to PR it, I for one don't have the time for pedantry

**Comment by DaedalusGame** [comment]
Listen 'ere bucko
First of all, the forge devs know about it and have known for months now, and as it's not fixed they either care as much as we do or think it's working as intended
Second of all, we can't mess with advancements because forge refuses to provide hooks for it ("use the jsons")
And also there's no interest in "fixing" something that has no actual impact on the quality of the "product"
And also we do this for free and hot pockets, send hot pockets to PO 1999118999117253

**Comment by mankra** [comment]
A log file that's full of errors because the devs are ignoring them is against its purpose and provocates further bug reports that also have to be ignored in the future. That's absurd. You are really weird programmers.

KnightMiner posted a solution which sounds easy. I don't understand your problem here.
